#!/usr/bin/bash

# ━━━━━━━━━━━━[ 🎨 Color Definitions ]━━━━━━━━━━━━
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;36m'
NC='\033[0m' # No Color

prompt_table_name() {
    while true
    do
        read -p "$(echo -e "${BLUE}📘 Enter table name to create (or type '0' to go back): ${NC}")" tableName

        if [[ $tableName == "0" ]]; then
            echo -e "${YELLOW}⚠️  Returning to previous menu...${NC}"
            exit 1
        fi

        if ! validate_table_name $tableName; then
            pause
            continue
        fi

        if table_exists $dbName $tableName; then
            echo -e "${YELLOW}⚠️  Table with the same name already exists. Choose another one!${NC}"
            pause
            continue
        fi

        break
    done
}

validate_table_name() {
    if [[ -z "$tableName" ]]; then
        echo -e "${RED}❌ You must enter a table name!${NC}"
        return 1
    fi

    local result
    result=$(./inputValidator CHARS_ONLY "$tableName")

    if [[ $result != "0" ]]; then
        echo -e "${RED}❌ Table name should be any combination of letters from A to Z or a to z${NC}"
        return 1
    fi

    return 0
}

table_exists() {
    [[ -f "./mydb/$dbName/$tableName" ]]
}

pause() {
    read -r -p "$(echo -e "${YELLOW}⚠️  Press any key to continue...${NC}")" -n1 -s
    echo
}

create_table_files() {
    echo -e "${BLUE}📘 Creating table files...${NC}"
    touch "./mydb/$dbName/$tableName" "./mydb/$dbName/.$tableName.metadata"
    echo -e "${GREEN}✅ Table files created successfully.${NC}"
}

main() {
    dbName=$1
    if [[ -z "$dbName" ]]; then
        echo -e "${RED}❌ Database name is required${NC}"
        exit 1
    fi

    echo -e "${BLUE}━━━━━━━━━━━━[ 📘 Create Table in '$dbName' ]━━━━━━━━━━━━${NC}"
    prompt_table_name
    create_table_files
    ./addTableColumn "$dbName" "$tableName"
    exit 0
}

main $@
